name: alphabetes
description: A kid game with animals.

version: 0.2.3

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_icons: ^1.0.0+1
  provider: ^4.0.2
  shared_preferences: ^0.5.3+4
  giffy_dialog: ^1.7.0
  lottie: ^0.2.0
  flutter_tts: ^0.8.7
  audioplayers: ^0.14.0
  fluttertoast: ^3.1.3
  package_info: ^0.4.0+4
  avatar_glow: ^1.1.0
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/videos/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
